name: prompts_framework_mcp
description: MCP server providing strategic guidance for AI agents managing
  Agentic Executables (AE) framework
version: 0.1.0
repository: https://github.com/fluent-meaning-symbiotic/agentic_executables
issue_tracker: https://github.com/fluent-meaning-symbiotic/agentic_executables/issues
documentation: https://github.com/fluent-meaning-symbiotic/agentic_executables/blob/main/README.md
homepage: https://github.com/fluent-meaning-symbiotic/agentic_executables
license: MIT

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dart_mcp: ^0.3.3
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  xsoulspace_lints: ^0.1.2

executables:
  prompts_framework_mcp_server: prompts_framework_mcp_server
