name: prompts_framework_mcp
description: MCP server exposing @prompts_framework/ as tools and resources.
version: 0.1.0
publish_to: none
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  dart_mcp: ^0.3.3
  path: ^1.9.0
  yaml: ^3.1.2
  meta: ^1.15.0
  collection: ^1.18.0
  async: ^2.11.0
dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
executables:
  prompts_framework_mcp: bin/prompts_framework_mcp.dart
